export enum CoreStateEnum {
    BEFORE_INITIALIZATION_STARTED,
    BEFORE_INITIALIZATION_DONE,
    INITIALIZATION_STARTED,
    INITIALIZATION_DONE,
    READY,
    DESTRUCTION_STARTED,
    DESTRUCTION_DONE
}
